### ISSUE TITLE
Task7 - Gradle Wrapper and Github Actions configuration (subsection 1-3)

### ISSUE THREAD

**Issue by szymonone** [DanutaHer/invoicing-system-danuta-hering#15]
1)    Update version of Gradle Wrapper to latest available
2)    Introduce Gradle ToolChains configuration and use it with latest compatible version of Java
3)    Remove the Java setup from Github Actions configuration

**Comment by szymonone** [comment]
hej, trochę poza tym PR ale na masterze w repo zdalnym jest drobna literówka na pakiecie - futurecollarc zamiast futurecollars - zmieniam u siebie na lokalnym - > będzie w kolejnym PR.

**Comment by DanutaHer** [comment]
Jest już to zmienione w PR do zadania 6
